disabled_rules: # rule identifiers to exclude from running
  - trailing_newline
  - opening_brace
  - custom_rules
  - empty_count
  - type_name
  - function_body_length
  - nesting
  - identifier_name
  - operator_whitespace
  - control_statement
  - return_arrow_whitespace
  - closing_brace
  - statement_position
  - type_body_length
  - todo
  - legacy_constructor
  - missing_docs
  - file_length
  - leading_whitespace
  - function_parameter_count
  - trailing_whitespace
  - implicit_getter

opt_in_rules: # some rules are only opt-in
  - force_unwrapping
  - force_cast
  - force_try
  - comma
  - cyclomatic_complexity
  - legacy_constant
  - trailing_semicolon
  - colon
  - number_separator
  - line_length
  # - file_header
 
included: # paths to include during linting. `--path` is ignored if present.
  - MathTutor
  - Pods/BCGSMobilePackage

excluded:

# file_header:
#   required_pattern: |
#                     \/\/
#                     \/\/  .*?\.swift
#                     \/\/  SwiftLint
#                     \/\/
#                     \/\/  Created by .*? on \d{1,2}\/\d{1,2}\/\d{2}\.
#                     \/\/  Copyright © \d{4} Realm\. All rights reserved\.
#                     \/\/
identifier_name:
  excluded:
    - id
line_length: 120
number_separator:
  minimum_length: 5
